active_features:
- mean
- std
- peak
data:
  num_samples_to_load: 2000000
  offline_dataset_path: asl_offline_dataset_10M_baseline_v1
  pld_values:
  - 500
  - 1000
  - 1500
  - 2000
  - 2500
  - 3000
  use_offline_dataset: true
data_noise_components:
- thermal
- physio
- drift
experiment_hypothesis: Does Peak height help even more when noise is messy?
simulation:
  T1_artery: 1850.0
  T2_factor: 1.0
  T_tau: 1800.0
  alpha_BS1: 1.0
  alpha_PCASL: 0.85
  alpha_VSASL: 0.56
  pld_values:
  - 500
  - 1000
  - 1500
  - 2000
  - 2500
  - 3000
training:
  batch_size: 4096
  dropout_rate: 0.1
  early_stopping_min_delta: 0.0
  early_stopping_patience: 10
  encoder_type: physics_processor
  hidden_sizes:
  - 256
  - 128
  - 64
  learning_rate: 0.0003
  model_class_name: DisentangledASLNet
  n_ensembles: 1
  n_epochs: 50
  norm_type: batch
  transformer_d_model_focused: 32
  transformer_nhead_model: 4
  transformer_nlayers_model: 2
  validation_steps_per_epoch: 25
  weight_decay: 0.0001
wandb:
  wandb_entity: adikondepudi
  wandb_project: asl-ablation-study
